language: go
go:
- 1.8
script:
- echo ""
after_success:
- bin/build_all
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: n945Pyjp56ZmPW4LsH22emN5ltO+MXTxb/qTJ409rsIWueky80s2K96Jd0a6mEctniOQQJO5BJGbok0AxKArQt3GxCDNyfg+BGhCmrwcD3HwCH2UZQ6Qt35tj4s75deCl1SknNymL/TQE5QIj1NCd1kdmO/+9ZAXXYVSwc//5yZxpXcgZzvF560zozg9LeiWig/3H0j+r5cLH0pt0f6xS9ZBb9vixDnstcai1jKvCQlpguGUwnTKgO0LlQ25UjcV6j8S4zy/lQXEn9ZiKxsbdGsedljqzuFa2COUK4KPCYtJ67FvFLmTg0V3zeg/YQUwa6hCt3bbRIdo0sVAI2D1zjx3mMmLNp+o6zSEAOpuj/SAu5LNjQ1RzQkpdNTplFWkJu0P5wlpWgTFsru1oeMG4hOcB+IZLmtoKixI1o+lRXb5BAReDTe6D5sc15wTKX16br7Tn2d7grvIDzeHLqwMj9WlUGez0i1il5rV12wqte5b5pPI+Ztn71k25lZfxjMBmJEGhKd3jMEMu5jtJ6R2lWzgi8c4TPJ5JZF0iHR8E+fpRQ8A++Q0pH7hyQO0QR0J8tdnZKtliTtNdr1WLptF9MNCbBCg/KzVle9C/QV0+f/ziKaFQDnelydDaA2EhozaDJdNUFrBh/uoA8Mk3qO9B8Pst7LHUhp2TdWp9/e9qso=
  file:
  - out/accept-mr_darwin_amd64
  - out/accept-mr_linux_386
  - out/accept-mr_linux_amd64
  - out/accept-mr_windows_386.exe
  - out/accept-mr_windows_amd64.exe
  on:
    tags: true
    all_branches: true
