language: go
go:
  - '1.13'
script:
  - echo ""
after_success:
  - export GO111MODULE=on
  - bin/build_all
deploy:
  provider: releases
  api_key:
    secure: U3sINUl7YCPxy8Qjuqj3q7Mg+UD7BKMYu9qvzu6zG4+9kkaEy7Fm/prfCJC8BEUGrB1xsneIKJR8MVB6sXZVmzZQfwmxplTKJ2paCHUHLpjbJWR54vd82EUiqjL5IJfY/1HjBVcwcilyCj4JWytLKZZmSmJ8iGK7ywV34J6GsqjQIA6jgcygktJh92e9YK7QusfRcN9q12fvxJEs6g/6z5jBWG7hmQlNqVEfbP8Reyebv5mQnHfzOvBFR+ZDOh+vONJi7mKbgCDZcH9VryjEi1HbUsXkF8wKamNgH0DKeAquZBWUO/PkScJg2j5Ss/XTcI7bixw/T59nZ7VEY5tgmolHNy5UjFR6b840Os0LirB7LITOWIVDeR3TIwqGc8GTJfonLsZ4Qw6OvakRZm2+wrypBLDRX7fTnSpf31+Obkih79ckMhnJHiXlrtiiybMBTf1nLw0Ujq0Lr+KuFAkjrx+HYZNOMAU9sbonG1pDjRk83SjqX2PVD3T9K96Tfk4ZOysiqrVxuJHQkGf+Nt4Xve7AMl0fgmuYkmqeoQfJyoroYJPeaEmYoMYdw2qrBPOtw/GESmmE1Q9ody44pMWTzibqtYYl66lGZBGUJYPF/MBkkFvp4gAWAHE/HaTtXxogZlERl6A6thQMl6ch7ccYfM3cgnaWZfrSWT88oUfzMko=
  file_glob: true
  file:
    - 'out/*'
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
